name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install -y libtinfo6 libncurses6 openjdk-17-jdk

      - name: Accept Android licenses
        run: |
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FloraDaily-APK
          path: bin/*.apk
